## Slingshot Common Messages
## RA-11: Originally copied from Share, and everything except the
## required role.* and hybridsync.* properties removed.

## Roles
role.SiteManager=Gerente
role.SiteCollaborator=Colaborador
role.SiteContributor=Contribuidor
role.SiteConsumer=Consumidor

#Hybrid Sync Console
hybridsync.ssd-id-header-label=ID de Sincroniza\u00e7\u00e3o
hybridsync.ssd-failed-reason-header-label=Tipo de Falha na Sincroniza\u00e7\u00e3o
hybridsync.path-desc-header-label=Localiza\u00e7\u00e3o de Item Original
hybridsync.sync-creator-header-label=Criador de Sincroniza\u00e7\u00e3o
hybridsync.cloud-user-header-label=Usu\u00e1rio de Nuvem
hybridsync.remote-tenant-id-header-label=Rede de Nuvem
hybridsync.target-folder-node-ref-header-label=Destino de Nuvem
hybridsync.actions-header-label=A\u00e7\u00f5es

sync.folder.name_clash=Conte\u00fado com o mesmo nome j\u00e1 existe na pasta de destino.
sync.folder.not_found=N\u00e3o \u00e9 poss\u00edvel localizar a pasta.
sync.node.already_synced=N\u00e3o \u00e9 poss\u00edvel criar conte\u00fado: j\u00e1 foi sincronizado a partir de outra localiza\u00e7\u00e3o.
sync.node.other_sync_set=Este conte\u00fado j\u00e1 foi sincronizado a partir de outra localiza\u00e7\u00e3o.
sync.node.no_longer_exists=Esse conte\u00fado n\u00e3o existe mais no Alfresco Content Services in the Cloud.
sync.node.no_longer_exists.description=Esse conte\u00fado n\u00e3o existe mais no Alfresco Content Services in the Cloud. Clique em Solicitar sincroniza\u00e7\u00e3o para tentar novamente.
sync.node.unknown=Encontramos um problema. Tente novamente.
sync.node.unknown.description=Ocorreu um erro inesperado. Causa: {0}.
sync.node.access_denied=N\u00e3o \u00e9 poss\u00edvel sincronizar o conte\u00fado: voc\u00ea n\u00e3o tem permiss\u00e3o para acessar o arquivo de destino.
sync.node.access_denied_source=N\u00e3o \u00e9 poss\u00edvel sincronizar o conte\u00fado: voc\u00ea n\u00e3o tem permiss\u00e3o para acessar o arquivo de origem.
sync.node.content_limit_violation=Esse arquivo ultrapassa o limite de conte\u00fado. O arquivo \u00e9 muito grande para executar a a\u00e7\u00e3o.
sync.node.quota_limit_violation=Voc\u00ea ultrapassou a cota de conte\u00fado. N\u00e3o h\u00e1 espa\u00e7o livre suficiente para executar a a\u00e7\u00e3o.
sync.node.authentication_error=N\u00e3o \u00e9 poss\u00edvel sincronizar o conte\u00fado com a nuvem: os detalhes de autentica\u00e7\u00e3o n\u00e3o s\u00e3o v\u00e1lidos.
sync.node.authentication_error.description=N\u00e3o \u00e9 poss\u00edvel sincronizar o conte\u00fado com a nuvem: os detalhes de autentica\u00e7\u00e3o do usu\u00e1rio {0} n\u00e3o s\u00e3o v\u00e1lidos.
sync.node.owner_not_found=N\u00e3o conseguimos sincronizar o conte\u00fado porque o propriet\u00e1rio foi removido ou deletado.
sync.node.owner_not_found.description=O usu\u00e1rio que possui esta sincroniza\u00e7\u00e3o, {0}, n\u00e3o existe mais. Clique em Dessincronizar.

sync.communications.error=N\u00e3o \u00e9 poss\u00edvel se comunicar com o sistema remoto
sync.communications.error.description=N\u00e3o \u00e9 poss\u00edvel se comunicar com o sistema remoto. A sincroniza\u00e7\u00e3o funcionar\u00e1 automaticamente quando as comunica\u00e7\u00f5es voltarem a funcionar
